Repository HSU-NIMBUS2000/Pyeoning-Backend, pull requests merged in 2024-11, with the labels that each got.

#10 ✨ FEAT. 환자 등록 API 구현
  .gradle/8.10.2/checksums/checksums.lock
  .gradle/8.10.2/checksums/md5-checksums.bin
  .gradle/8.10.2/checksums/sha1-checksums.bin
  .gradle/8.10.2/executionHistory/executionHistory.bin
  .gradle/8.10.2/executionHistory/executionHistory.lock
  .gradle/8.10.2/fileHashes/fileHashes.bin
  .gradle/8.10.2/fileHashes/fileHashes.lock
  .gradle/8.10.2/fileHashes/resourceHashesCache.bin
  .gradle/buildOutputCleanup/buildOutputCleanup.lock
  .gradle/buildOutputCleanup/outputFiles.bin
  .gradle/file-system.probe
  .vscode/settings.json
  build.gradle
  build/tmp/compileJava/compileTransaction/stash-dir/CheckLicenseDto.class.uniqueId0
  build/tmp/compileJava/compileTransaction/stash-dir/DoctorController.class.uniqueId4
  build/tmp/compileJava/compileTransaction/stash-dir/DoctorRegisterDto.class.uniqueId3
  build/tmp/compileJava/compileTransaction/stash-dir/DoctorService.class.uniqueId1
  build/tmp/compileJava/compileTransaction/stash-dir/DoctorServiceImpl.class.uniqueId2
  build/tmp/compileJava/compileTransaction/stash-dir/PatientServiceImpl.class.uniqueId0
  build/tmp/compileJava/previous-compilation-data.bin
  build/tmp/compileTestJava/previous-compilation-data.bin
  src/main/java/com/hsu/pyeoning/domain/patient/service/PatientService.java
  src/main/java/com/hsu/pyeoning/domain/patient/service/PatientServiceImpl.java
  src/main/java/com/hsu/pyeoning/domain/patient/web/controller/PatientController.java
  src/main/java/com/hsu/pyeoning/domain/patient/web/dto/PatientRegisterDto.java
  src/main/java/com/hsu/pyeoning/global/security/config/SecurityConfig.java
Labels: hanbin⛄️, ✨feat

#14 Feat#13 patient edit prompt
  .gradle/8.10.2/executionHistory/executionHistory.bin
  .gradle/8.10.2/executionHistory/executionHistory.lock
  .gradle/8.10.2/fileHashes/fileHashes.bin
  .gradle/8.10.2/fileHashes/fileHashes.lock
  .gradle/8.10.2/fileHashes/resourceHashesCache.bin
  .gradle/buildOutputCleanup/buildOutputCleanup.lock
  .gradle/file-system.probe
  build/tmp/compileJava/compileTransaction/stash-dir/PatientServiceImpl.class.uniqueId0
  build/tmp/compileJava/compileTransaction/stash-dir/SecurityConfig.class.uniqueId0
  build/tmp/compileJava/previous-compilation-data.bin
  src/main/java/com/hsu/pyeoning/domain/patient/entity/Patient.java
  src/main/java/com/hsu/pyeoning/domain/patient/service/PatientService.java
  src/main/java/com/hsu/pyeoning/domain/patient/service/PatientServiceImpl.java
  src/main/java/com/hsu/pyeoning/domain/patient/web/controller/PatientController.java
  src/main/java/com/hsu/pyeoning/domain/patient/web/dto/ModifyPromptDto.java
Labels: hanbin⛄️, ✨feat

#19 Feat/#18 patient doctor info
  .gradle/8.10.2/executionHistory/executionHistory.bin
  .gradle/8.10.2/executionHistory/executionHistory.lock
  .gradle/8.10.2/fileHashes/fileHashes.bin
  .gradle/8.10.2/fileHashes/fileHashes.lock
  .gradle/8.10.2/fileHashes/resourceHashesCache.bin
  .gradle/buildOutputCleanup/buildOutputCleanup.lock
  .gradle/file-system.probe
  build/tmp/compileJava/previous-compilation-data.bin
  src/main/java/com/hsu/pyeoning/domain/doctor/web/dto/DoctorInfoDto.java
  src/main/java/com/hsu/pyeoning/domain/patient/service/PatientService.java
  src/main/java/com/hsu/pyeoning/domain/patient/service/PatientServiceImpl.java
  src/main/java/com/hsu/pyeoning/domain/patient/web/controller/PatientController.java
Labels: hanbin⛄️, ✨feat

#22 ✨ FEAT. 요약보고서 조회 기능
  src/main/java/com/hsu/pyeoning/domain/doctor/service/DoctorServiceImpl.java
  src/main/java/com/hsu/pyeoning/domain/summary/entity/Summary.java
  src/main/java/com/hsu/pyeoning/domain/summary/repository/SummaryRepository.java
  src/main/java/com/hsu/pyeoning/domain/summary/service/SummaryService.java
  src/main/java/com/hsu/pyeoning/domain/summary/service/SummaryServiceImpl.java
  src/main/java/com/hsu/pyeoning/domain/summary/web/controller/SummaryController.java
  src/main/java/com/hsu/pyeoning/global/security/jwt/JwtTokenProvider.java
Labels: jungeun🎃, ✨feat

#23 ✨ FEAT. 대화 내용 전체 조회
  src/main/java/com/hsu/pyeoning/domain/chat/entity/Chat.java
  src/main/java/com/hsu/pyeoning/domain/chat/repository/ChatRepository.java
  src/main/java/com/hsu/pyeoning/domain/chat/service/ChatService.java
  src/main/java/com/hsu/pyeoning/domain/chat/service/ChatServiceImpl.java
  src/main/java/com/hsu/pyeoning/domain/chat/web/controller/ChatController.java
Labels: jungeun🎃, ✨feat

#25 ♻️ REFACTOR. 대화 내용 및 요약보고서 조회 코드 리팩토링
  src/main/java/com/hsu/pyeoning/domain/chat/service/ChatServiceImpl.java
  src/main/java/com/hsu/pyeoning/domain/chat/web/dto/ChatDto.java
  src/main/java/com/hsu/pyeoning/domain/summary/service/SummaryServiceImpl.java
  src/main/java/com/hsu/pyeoning/domain/summary/web/dto/SummaryDto.java
Labels: jungeun🎃, ♻️refactor

#29 ✨ FEAT. 대화 내용 전체 조회 (환자 페이지)
  src/main/java/com/hsu/pyeoning/domain/chat/repository/ChatRepository.java
  src/main/java/com/hsu/pyeoning/domain/chat/service/ChatService.java
  src/main/java/com/hsu/pyeoning/domain/chat/service/ChatServiceImpl.java
  src/main/java/com/hsu/pyeoning/domain/chat/web/controller/ChatController.java
  src/main/java/com/hsu/pyeoning/global/security/config/SecurityConfig.java
Labels: jungeun🎃, ✨feat

#33 🚨 FIX. 환자 등록 JWT 필터링 수정
  src/main/java/com/hsu/pyeoning/global/security/jwt/filter/JwtTokenFilter.java
Labels: :rotating_light: fix, jungeun🎃

#35 🚨 FIX. 의사 회원가입시 이메일 받기
  src/main/java/com/hsu/pyeoning/domain/doctor/entity/Doctor.java
  src/main/java/com/hsu/pyeoning/domain/doctor/service/DoctorServiceImpl.java
  src/main/java/com/hsu/pyeoning/domain/doctor/web/dto/DoctorRegisterDto.java
Labels: :rotating_light: fix, jungeun🎃

#38 ✨ FEAT. 세션 종료 기능 구현
  src/main/java/com/hsu/pyeoning/domain/chat/entity/Chat.java
  src/main/java/com/hsu/pyeoning/domain/chat/repository/ChatRepository.java
  src/main/java/com/hsu/pyeoning/domain/chat/service/ChatService.java
  src/main/java/com/hsu/pyeoning/domain/chat/service/ChatServiceImpl.java
  src/main/java/com/hsu/pyeoning/domain/chat/web/controller/ChatController.java
Labels: ✨feat, :christmas_tree:khyaejin

#40 ✨ FEAT. 요약보고서 생성 api 구현(통신 제외) & 🚨 FIX. UnauthorizedException 관련 추가
  src/main/java/com/hsu/pyeoning/domain/chat/repository/ChatRepository.java
  src/main/java/com/hsu/pyeoning/domain/chat/service/ChatServiceImpl.java
  src/main/java/com/hsu/pyeoning/domain/chat/web/dto/ChatMessageRequestDto.java
  src/main/java/com/hsu/pyeoning/domain/summary/service/SummaryService.java
  src/main/java/com/hsu/pyeoning/domain/summary/service/SummaryServiceImpl.java
  src/main/java/com/hsu/pyeoning/domain/summary/web/controller/SummaryController.java
  src/main/java/com/hsu/pyeoning/domain/summary/web/dto/ChatSummaryFastApiRequestDto.java
  src/main/java/com/hsu/pyeoning/domain/summary/web/dto/ChatSummaryResponseDto.java
  src/main/java/com/hsu/pyeoning/global/exception/GlobalExceptionController.java
  src/main/java/com/hsu/pyeoning/global/exception/UnauthorizedException.java
  src/main/java/com/hsu/pyeoning/global/security/jwt/JwtTokenProvider.java
Labels: :rotating_light: fix, ✨feat, :christmas_tree:khyaejin

#41 ✨ FEAT. 펴닝과의 채팅 api 구현 완료 - 통신 완료
  src/main/java/com/hsu/pyeoning/domain/chat/entity/Chat.java
  src/main/java/com/hsu/pyeoning/domain/chat/service/ChatServiceImpl.java
  src/main/java/com/hsu/pyeoning/domain/chat/web/dto/ChatMessageFastApiRequestDto.java
  src/main/java/com/hsu/pyeoning/domain/chat/web/dto/ChatMessageFastApiResponseDto.java
  src/main/java/com/hsu/pyeoning/domain/summary/web/dto/ChatSummaryFastApiRequestDto.java
  src/main/java/com/hsu/pyeoning/global/api/dto/ChatHistory.java
  src/main/java/com/hsu/pyeoning/global/security/config/RestTemplateConfig.java
Labels: ✨feat, :christmas_tree:khyaejin

#45 ✨ FEAT. 요약보고서 생성 api 구현 완료 - 통신 완료
  src/main/java/com/hsu/pyeoning/domain/summary/service/SummaryServiceImpl.java
Labels: ✨feat, :christmas_tree:khyaejin

#47 🚨 FIX. 환자 등록 후 첫 요약보고서 생성 불가 오류 해결
  src/main/java/com/hsu/pyeoning/domain/patient/service/PatientServiceImpl.java
Labels: :rotating_light: fix, :christmas_tree:khyaejin

#51 ✨ FEAT. CORS 설정 추가
  build.gradle
  src/main/java/com/hsu/pyeoning/global/security/config/WebConfig.java
Labels: jungeun🎃, ✨feat

#53 🎨 CHORE. 의사 등록시 전화번호 받기
  src/main/java/com/hsu/pyeoning/domain/doctor/entity/Doctor.java
  src/main/java/com/hsu/pyeoning/domain/doctor/service/DoctorServiceImpl.java
  src/main/java/com/hsu/pyeoning/domain/doctor/web/dto/DoctorRegisterDto.java
Labels: :rotating_light: fix, jungeun🎃

#54 🚨 impl직접참조 수정, 어노테이션 추가
  src/main/java/com/hsu/pyeoning/domain/chat/web/controller/ChatController.java
  src/main/java/com/hsu/pyeoning/domain/doctor/service/DoctorServiceImpl.java
  src/main/java/com/hsu/pyeoning/domain/patient/service/PatientServiceImpl.java
Labels: :rotating_light: fix, hanbin⛄️

#56 :sparkles: 환자코드이메일전송
  build.gradle
  src/main/java/com/hsu/pyeoning/domain/patient/service/PatientServiceImpl.java
Labels: hanbin⛄️, ✨feat

#59 🚨 fix/#57 modifyPrompt api
  src/main/java/com/hsu/pyeoning/domain/patient/service/PatientServiceImpl.java
  src/main/java/com/hsu/pyeoning/domain/patient/web/controller/PatientController.java
  src/main/java/com/hsu/pyeoning/domain/patient/web/dto/ModifyPromptDto.java
Labels: :rotating_light: fix, hanbin⛄️

#60 🚨 FIX. 크롬 정책으로 인한 token 삽입 위치 변경
  app.log
  src/main/java/com/hsu/pyeoning/domain/chat/service/ChatService.java
  src/main/java/com/hsu/pyeoning/domain/chat/service/ChatServiceImpl.java
  src/main/java/com/hsu/pyeoning/domain/chat/web/controller/ChatController.java
  src/main/java/com/hsu/pyeoning/domain/chat/web/dto/SessionEndRequestDto.java
  src/main/java/com/hsu/pyeoning/domain/summary/entity/Summary.java
  src/main/java/com/hsu/pyeoning/domain/summary/web/controller/SummaryController.java
  src/main/java/com/hsu/pyeoning/global/exception/GlobalExceptionController.java
  src/main/java/com/hsu/pyeoning/global/security/jwt/filter/JwtTokenFilter.java
  src/main/java/com/hsu/pyeoning/global/security/jwt/util/AuthenticationUserUtils.java
Labels: :rotating_light: fix, :christmas_tree:khyaejin

#62 ✨ FEAT.환자리스트검색기능추가
  src/main/java/com/hsu/pyeoning/domain/patient/repository/PatientRepository.java
  src/main/java/com/hsu/pyeoning/domain/patient/service/PatientService.java
  src/main/java/com/hsu/pyeoning/domain/patient/service/PatientServiceImpl.java
  src/main/java/com/hsu/pyeoning/domain/patient/web/controller/PatientController.java
Labels: hanbin⛄️, ✨feat

#64 ✨ Feat.대화패턴추적 기능 추가
  src/main/java/com/hsu/pyeoning/domain/chat/repository/ChatRepository.java
  src/main/java/com/hsu/pyeoning/domain/patient/service/PatientService.java
  src/main/java/com/hsu/pyeoning/domain/patient/service/PatientServiceImpl.java
  src/main/java/com/hsu/pyeoning/domain/patient/web/controller/PatientController.java
  src/main/java/com/hsu/pyeoning/domain/risk/entity/RiskLevel.java
  src/main/java/com/hsu/pyeoning/domain/risk/repository/RiskLevelRepository.java
  src/main/java/com/hsu/pyeoning/domain/risk/web/dto/RiskLevelResponseDto.java
  src/main/java/com/hsu/pyeoning/domain/summary/service/SummaryServiceImpl.java
  src/main/java/com/hsu/pyeoning/domain/summary/web/dto/ChatSummaryFastApiResponseDto.java
  src/main/java/com/hsu/pyeoning/global/security/config/SecurityConfig.java
Labels: hanbin⛄️, ✨feat

#66 ✨ FEAT. 요약보고서 생성 - 위험도 측정 기능 추가
  app.log
  src/main/java/com/hsu/pyeoning/domain/doctor/entity/Doctor.java
  src/main/java/com/hsu/pyeoning/domain/summary/service/SummaryServiceImpl.java
  src/main/java/com/hsu/pyeoning/domain/summary/web/dto/ChatSummaryFastApiResponseDto.java
  src/main/java/com/hsu/pyeoning/domain/summary/web/dto/ChatSummaryResponseDto.java
Labels: ✨feat, :christmas_tree:khyaejin

#68 ✏️ FIX. ignore 파일에 app.log 파일 추가
  .gitignore
  app.log
Labels: :christmas_tree:khyaejin

#73 Fix/#72
  src/main/java/com/hsu/pyeoning/domain/patient/service/PatientServiceImpl.java
  src/main/java/com/hsu/pyeoning/domain/patient/web/controller/PatientController.java
  src/main/java/com/hsu/pyeoning/domain/patient/web/dto/PatientDetailDto.java
Labels: :rotating_light: fix, hanbin⛄️
